# Generated by Django 5.0 on 2024-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='热点标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='详情页URL')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据来源')),
            ],
        ),
    ]
